steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/voting-app-backend', '.']
  dir: 'voting-app-backend'  # Specify the directory containing Dockerfile
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/voting-app-backend']
images:
- 'gcr.io/$PROJECT_ID/voting-app-backend'
options:
  logging: CLOUD_LOGGING_ONLY
