steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/voting-app-backend', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/voting-app-backend']
images:
- 'gcr.io/$PROJECT_ID/voting-app-backend'
options:
  logging: CLOUD_LOGGING_ONLY
